[phases.setup]
nixPkgs = ['python311', 'postgresql']

[phases.install]
cmds = [
    'pip install --upgrade pip',
    'pip install -r requirements/production.txt'
]

[phases.build]
cmds = [
    'python manage.py collectstatic --noinput --settings=majobacore.settings.production'
]

[start]
cmd = 'python manage.py migrate --settings=majobacore.settings.production --noinput && gunicorn majobacore.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --timeout 120 --access-logfile - --error-logfile -'
