[build]
builder = "NIXPACKS"
buildCommand = "python manage.py collectstatic --noinput --settings=majobacore.settings.production"

[deploy]
healthcheckPath = "/health/live/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
